### ISSUE TITLE
Implement sort -h option to support sort by human readable size

### ISSUE THREAD

**Issue by HuangShumin** [landley/toybox#184] opened 2020-04-17 03:02 UTC
just let `du -sh | sort -h' work

**Comment by kasperk81** [comment] 2021-06-29 22:38
u mean `du -h | sort -h` right?

**Comment by HuangShumin** [comment] 2021-06-30 06:48
YES

**Comment by landley** [comment] 2021-06-30 18:09
How do the fallback sorts work, and are the numbers REQUIRED to be human readable? (As in will 1024 compare equal to 1k? It does not look like it will...)

**Comment by enh-google** [comment] 2021-06-30 18:54
one random note i have here is that when i looked at whether bionic should add the GNU [strverscmp(3)](https://man7.org/linux/man-pages/man3/strverscmp.3.html) extension, the documentation for that and the coreutils documentation described slightly different algorithms. which led me to think "no, this isn't something i should implement, because toybox will probably end up having to do this itself anyway [see also: the BSDs and macOS], and adding yet another implementation to bionic [with no prospective users] seems like it would just add to an already confusing situation". (fwiw, musl _does_ implement strverscmp() but i don't remember whether i did any testing to compare it to glibc and coreutils.)

**Comment by landley** [comment] 2021-06-30 20:29
The problem _I_ hit is that different sort versions sort differently! There's version skew in there (which broke my existing -V test and I'm tempted to just comment it out, but I should probably match current instead).

There's no spec for this. Whatever the other implementation does is the spec. And the frustrating part is THEY CHANGED. Grrr.

**Comment by kasperk81** [comment] 2021-06-30 20:35
Yes, unless there is a published spec for this sort of thing it's not worth the effort to chase $some_other unwarranted implementations out in the wild. #wontfix is the right answer here from my viewpoint.

**Comment by landley** [comment] 2021-06-30 20:39
Except "What does Debian Do" is kinda relevant, especially since Red Hat gave up on pursuing developer desktops (as a side effect of eating Sun's lunch and pursuing the Enterprise market) and Ubuntu surpassed them as the build system of choice for package maintainers.

(Red Hat and Debian use the same command line utility implementation for 90% of stuff, but Debian is what I'm regression testing against. The closest I can get to "standard reference linux" is a debootstrap chroot...)

**Comment by kasperk81** [comment] 2021-06-30 20:55
coreutils has these cases covered in tests https://github.com/coreutils/coreutils/blob/00ea4bacf6063ccc125209d5186f8f2382c6f0d4/tests/misc/sort.pl#L57-L80, it might be enough for (so-called) conformance coverage.

**Comment by landley** [comment] 2021-12-31 06:34
FYI commit e28e5bb465f7 was a first stab at this.

**Closed** 2021-12-31 10:39 UTC

**Comment by kasperk81** [comment] 2022-01-01 13:31
not there yet
```sh
$ cat > list<<EOF
320K    ./x1
412K    ./x2
2.6M    .
952K    ./x3
764K    ./x4
EOF

# coreutils / Debian
$ cat list | sort -h
320K    ./x1
412K    ./x2
764K	./x4
952K	./x3
2.6M	.

# toybox
$ cat list | toyboyx sort -h
2.6M	.
320K    ./x1
412K    ./x2
764K	./x4
952K	./x3
```
