### ISSUE TITLE
Segmentation Fault in sed 's' command if skipping initial match

### ISSUE THREAD

**Issue by whentze** [landley/toybox#192] opened 2020-05-06 11:50 UTC
toybox sed crashes with a segfault when given certain
substitution commands that specify to only substitute the nth match
where n > 1.

## Steps to reproduce

```
echo "e" | toybox sed -e "s/e//2"
```

## Analysis

In [sed.c:498](https://github.com/landley/toybox/blob/0.8.2/toys/posix/sed.c#L498), sed decides correctly that, since it is looking at the 1st match
but should only replace the nth match, the current match should be skipped.
To do so, it copies the remainder of the current line not covered by the match
into `l2`.
The memory for `l2` is allocated in [line 526](https://github.com/landley/toybox/blob/0.8.2/toys/posix/sed.c#L526), when carrying out a substitution.
However, if the first match already needs to be skipped, there have been
no substitutions yet and `l2` is still a null pointer, leading to the crash.

## Additional Information

This behavior was detected using techniques developed by the SYMBIOSYS research project at COMSYS
RWTH Aachen University. This research is supported by the European Research Council (ERC)
under the EU's Horizon 2020 Research and Innovation Programme grant agreement n. 647295 (SYMBIOSYS).

**Comment by kasperk81** [comment] 2021-04-26 08:19
We are also hitting this bug with sed, the arguments in our code are dynamic and switching to regular bash fixed the problem. Any chance this gets fixed in the next release?

**Comment by landley** [comment] 2021-04-26 09:31
Oh. Huh, I thought I'd already fixed this one.

(You're using a version of sed that's a bash builtin? I hadn't encountered that before...)

**Comment by landley** [comment] 2021-04-26 09:56
Commit 773d404ee2b9

**Comment by kasperk81** [comment] 2021-04-26 11:02
Thanks much, compiled and tested it. I can confirm that this bug is fixed.

aside, there were few warnings during the compilation,sharing  in case you want to track them (gcc 9.3 on ubuntu 20.04):
```sh
$ make defconfig
cc -o kconfig/conf kconfig/conf.c kconfig/zconf.tab.c -DKBUILD_NO_NLS=1 \
        -DPROJECT_NAME=\"ToyBox\"
In file included from kconfig/zconf.tab.c:2340:
kconfig/confdata.c: In function ‘conf_write’:
kconfig/confdata.c:435:20: warning: ‘.tmpconfig.’ directive writing 11 bytes into a region of size between 1 and 128 [-Wformat-overflow=]
  435 |   sprintf(tmpname, "%s.tmpconfig.%d", dirname, (int)getpid());
      |                    ^~~~~~~~~~~~~~~~~
kconfig/confdata.c:435:3: note: ‘sprintf’ output between 13 and 150 bytes into a destination of size 128
  435 |   sprintf(tmpname, "%s.tmpconfig.%d", dirname, (int)getpid());
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scripts/genconfig.sh
kconfig/conf -D /dev/null Config.in > /dev/null

$ make
scripts/make.sh
Generate headers from toys/*/*.c...
generated/newtoys.h
warning: using unfinished code from toys/pending
Library probe...........
Make generated/config.h from .config.
generated/flags.h generated/globals.h generated/tags.h generated/help.h
Compile toybox...................................toys/net/netstat.c: In function 'display_routes':
toys/net/netstat.c:254:3: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
  254 |   fgets(toybuf, sizeof(toybuf), fp);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
toys/net/netstat.c: In function 'show_ip':
toys/net/netstat.c:103:3: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
  103 |   fgets(toybuf, sizeof(toybuf), fp);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
toys/net/netstat.c: In function 'show_unix_sockets':
toys/net/netstat.c:173:3: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
  173 |   fgets(toybuf, sizeof(toybuf), fp);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......................................................................................toys/other/watchdog.c: In function 'watchdog_main':
toys/other/watchdog.c:48:5: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
   48 |     write(TT.fd, "", 1);
      |     ^~~~~~~~~~~~~~~~~~~
toys/other/watchdog.c: In function 'safe_shutdown':
toys/other/watchdog.c:34:3: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
   34 |   write(TT.fd, "V", 1);
      |   ^~~~~~~~~~~~~~~~~~~~
.......................................................................

$
```

**Comment by landley** [comment] 2021-04-27 06:22
kconfig/ is the kconfig plumbing copied from the 2.6 kernel a decade and a half ago. It's a built-time tool that just produces the .config file and nothing else, and there's a todo item to write a new one from scratch but it just doesn't matter enough to bother so far.

netstat is reading from /proc. If something bad is coming from /proc your kernel is compromised and there's nothing we can do about it in userspace, whatever build environment you have is being silly.

What exactly is watchdog.c supposed to do if the write() returns a problem? If you can't write to the watchdog driver the system will reboot, so WHATEVER action we take... the system will reboot. Again, your build environment is being silly. What strange flag did you send to it request that it complain about this stuff?

**Closed** 2021-04-27 08:14 UTC

**Comment by nykula** [comment] 2021-04-27 12:21
Since they mentioned Ubuntu, that flag is `-D_FORTIFY_SOURCE=2` from [Ubuntu-specific default compiler flags](https://wiki.ubuntu.com/ToolChain/CompilerFlags). Fedora maintainers [were considering](https://fedoraproject.org/wiki/Changes/HardenedCompiler) enabling the flag globally, but [rejected the change](https://pagure.io/releng/issue/8204) because it false positived on too many packages during their mass rebuild.

**Comment by enh-google** [comment] 2021-04-28 22:33
TIL that glibc's `__wur` isn't always on. yeah, you're right:
```
# if __USE_FORTIFY_LEVEL > 0
#  define __wur __attribute_warn_unused_result__
# endif
```

not that it makes much difference to me with my bionic maintainer hat on though, since Android's always `_FORTIFY_SOURCE=2` anyway. but, yeah, "how would we ever be able to turn this on?" is why i've done nothing on my "use `__attribute__((__warn_unused_result__))` in bionic" bug...

(but this does explain why the rest of the world hasn't fixed their warnings yet. i had been surprised that glibc going first on this one didn't seem to have moved the needle much.)

**Comment by kasperk81** [comment] 2021-04-28 23:17
>> warning: ignoring return value of 'fgets', declared with attribute warn_unused_result
>
> netstat is reading from /proc. If something bad is coming from /proc your kernel is compromised and there's nothing we can do about it in userspace, whatever build environment you have is being silly.

umm, not sure i follow the logic. my build environment is Ubuntu 20.04 standard install gcc 9.3, nothing customized or interesting here. the warning is simply referring to `fgets` result being ignored here: https://github.com/landley/toybox/blob/137ab99aa35a94ad1519b294906522ce108e3451/toys/net/netstat.c#L254 (which we can suppress in the user code / make config)

**Comment by enh-google** [comment] 2021-04-28 23:58
> umm, not sure i follow the logic.

it's a philosophical disagreement... `warn_unused_result` is saying "this call can fail in general, and you should check that". rob is saying "if this _specific_ call fails, your kernel is broken and there's nothing i can reasonably do". in both cases: for the fgets() the best we can do is say "your kernel is broken" and for write()s, and there's really no good outcome at all given what watchdog(1) is for.

i'm usually all for appeasing the compiler, even in low-value cases, so that i can keep the warning to guard against high value cases --- but even i struggle to think what we can do if a watchdog write() fails. ignoring the failure and hoping the next one works is probably the least worst option?

**Comment by kasperk81** [comment] 2021-04-29 00:15
>> your kernel is compromise
>
> the best we can do is say "your kernel is broken"

that's not necessarily the "best" thing to say. "we don't care about this warning" would be understandable. fgets on regular file can return NULL on error (see manual), but in case of /proc, it doesn't, but the compiler doesn't know/care about that when emitting the unused result warning, so it's a harmless warning not a "compromised kernel" ffs.

**Comment by landley** [comment] 2021-04-29 12:08
I have occasionally added typecasts to shut the compiler up, but typecasts don't reliably shut fortify up. (Because people were doing that, and the compiler guys got indignant that the programmers didn't believe the compiler writers universally knew better than the authors of each individual program.)

The point at which I stopped paying attention to fortify was when adding if (thingy); around the thingy that was doing a warning STILL DIDN'T SHUT FORTIFY UP. I had to do something _with_ the test result to avoid the warning. Maybe that's no longer the case, but that's the point where I stopped caring what they had to say.
