### ISSUE TITLE
find on btrfs goes into infinite loop when path is long

### ISSUE THREAD

**Issue by jacky8hyf** [landley/toybox#448] opened 2023-08-11 21:47 UTC
Repro steps:

1. Create a btrfs filesystem. I use a loop device. In my case, I did this:
    ```sh
    mkdir -p ~/btrfs/mount
    dd if=/dev/zero of=~/btrfs/btrfs.img bs=4M count=64
    mkfs.btrfs ~/btrfs/btrfs.img
    sudo mount -o loop=/dev/loop0 ~/btrfs/btrfs.img ~/btrfs/mount/
    ```
2. Enter the mount point, create a very long path, and create 2000 files in it:
    ```sh
    cd ~/btrfs/mount
    sudo chown $USER .
    mkdir -p xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    cd xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    for i in $(seq 1 2000); do touch $i; done
    ```
3. This enters an infinite loop (find, xargs, sed are all from toybox):
    ```sh
    find $(realpath .)  -type f | xargs -t -n1 sed -i'' -e '' # INFINITE LOOP
    ```
    It prints lines like the following from 1 to 2000 over and over again:
    ```
    sed -i -e  /home/elsk/btrfs/mount/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/1
    ```

Additional notes:

I think the issue is not in xargs, because the following also hangs (though without `xargs -t`, no output is shown).

```sh
find $(realpath .)  -type f -exec sed -i'' -e '' {} \; # HANGS
```

Also, if I replace the xargs in the command with the one from my host machine, the command also hangs.

I also don't think the issue is in sed. I replaced the sed command with a `perl` command:

```sh
find $(realpath .)  -type f | xargs -t -n1 perl -pi -e '' # INFINITE LOOP
```

(where find and xargs is from toybox and perl is from my host machine). The command prints lines that runs the perl command from 1~2000 over and over again. The same goes to

```sh
find $(realpath .)  -type f -exec perl -pi -e '' {} \; # HANGS
```

Hence, I think the issue is in `find`, but I am not 100% sure.

It only happens when the **path is very long**. For example, the following does not hang:

```sh
find . -type f | xargs -t -n1 sed -i'' -e '' # OKAY
```
... probably because the path of each found file is a relative path to `.`, not an absolute path that includes the super long path.

It only happens when there are **a lot of files**. For example, if I have 1000 files under the directory, the command correctly runs `sed` 1000 times. However, if I have around 1500 files in the directory, the command enters the loop multiple times, then eventually exits, after running `sed` about 2500 times (the number changes during every trial).

```sh
$ rm -f *
$ for i in $(seq 1 1500); do touch $i; done
# Number changes every time
$ find $(realpath .)  -type f | xargs -t -n1 sed -i'' -e '' 2>&1 | wc -l
2531
```

It doesn't happen with GNU findutils. If I replace find with the find from GNU findutils on my machine `find (GNU findutils) 4.9.0`, the issue does not reproduce.

It only happens with **btrfs** filesystem. We have multiple reports of this bug, all of them are on btrfs filesystem. I've also gone over the above repro steps on ext4, and the command exits properly.

**Comment by jacky8hyf** [comment] 2023-08-11 21:54
It doesn't matter if it is a single directory that is very long `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` or a deeply nested directory (e.g. when we discover the bug, the path was something like `out/bazel/output_user_root/b98a2e3cff634958873ab0c05622e734/sandbox/linux-sandbox/18/execroot/__main__/out/android-mainline/common/kernel/.tmp_cpio_dir`). Then, I notice that I just need a long path to trigger this bug, not necessary a deeply nested path.

**Comment by enh-google** [comment] 2023-08-11 22:46
dupe of #306 i think --- btrfs is known broken.

i assume this isn't anyone at Google who's hitting this? you don't have to say _which_ partner(s) in public, but i'm curious whether it's partners who're hitting this or just internet randos trying to build AOSP?

(either way, btrfs has definitely flipped my "will not use" bit, so you might want to advise them to get a non-broken fs instead!)

**Comment by landley** [comment] 2023-08-12 21:42
Also if you could add a note on the kernel bugzilla ticket to say that you hit it too: https://bugzilla.kernel.org/show_bug.cgi?id=217681

Maybe we need to email the kernel btrfs list? http://vger.kernel.org/vger-lists.html#linux-btrfs

**Comment by landley** [comment] 2023-08-12 22:21
I emailed linux-btrfs@vger.kernel.org with a cc: to enh, but I note that the vger entry above is still pointing to gmane.org which went down in either 2016 or 2020 depending how you want to count it according to https://en.wikipedia.org/wiki/Gmane and the spinics one A) hasn't updated in the past half hour and B) has a most recent post from a week ago, so... maybe it went through? Didn't get a bounce message or "held for moderation", although gmail's feral spam filter eats half of those no matter how many times I whap it on the nose with a rolled-up newspaper...

I can always email linux-kernel itself, which is a bit like trying to hitchhike on the side of an interstate these days...

**Comment by landley** [comment] 2023-08-12 23:30
Hey, it showed up: https://www.spinics.net/lists/linux-btrfs/msg138634.html

**Comment by landley** [comment] 2023-08-12 23:32
I'm gonna close this one as a dupe of 306.

**Closed by landley** 2023-08-12 23:32 UTC

**Comment by jacky8hyf** [comment] 2023-08-14 23:28
Thanks for triaging!

> dupe of #306 i think --- btrfs is known broken.
> 
> i assume this isn't anyone at Google who's hitting this? you don't have to say _which_ partner(s) in public, but i'm curious whether it's partners who're hitting this or just internet randos trying to build AOSP?
> 
> (either way, btrfs has definitely flipped my "will not use" bit, so you might want to advise them to get a non-broken fs instead!)

This is actually hit both internally by a Googler and externally by an SoC partner who tries to build the Android kernel. 

And thanks for bumping up https://bugzilla.kernel.org/show_bug.cgi?id=217681 ! Since it appears that a patch is already ready to be merged / already merged, I won't reply in that bugzilla.

**Comment by landley** [comment] 2023-08-14 23:39
It's in https://git.kernel.org/pub/scm/linux/kernel/git/kdave/linux.git/log/?h=for-next and missed the -rc6 pull by half a day but might still get pulled again for -rc7 before the 6.5 release. If not it should show up in 6.6.

I don't know why the patch is in that log twice (under two different commit numbers an hour apart) but assume they know what they're doing:

https://git.kernel.org/pub/scm/linux/kernel/git/kdave/linux.git/commit/?h=for-next&id=c5e6134bb363213ddadb65888eaa82fe76a707fc

https://git.kernel.org/pub/scm/linux/kernel/git/kdave/linux.git/commit/?h=for-next&id=9b378f6ad48cfa195ed868db9123c09ee7ec5ea2
