### ISSUE TITLE
[Documentation / FAQ entry] Relationship between toybox and busybox?

### ISSUE THREAD

**Issue by rubyFeedback** [landley/toybox#159] opened 2019-12-24 15:25 UTC
Hey Rob,

Not sure if it is important, but what is the relationship between toybox and
busybox? Or is the similar name just a coincidence?

If you'd have a bit of time, perhaps you could mention this briefly in the
FAQ of the main README.md. Hope that does not take away too much
time. :)

By the way, I have recently found mkroot, after looking for ways to abandon
glibc (for various reasons) in favour of musl. That was sort of my use case;
I already built (or am building) a customized LFS/BLFS variant that is a bit
similar to GoboLinux (versioned AppDir approach). Most of the toolchain
works, but glibc causes issues to me, so I am planning to make the switch
to musl one day, such as void has already done so. I also keep a statically
compiled busybox about - much easier to fix something and recover via
busyboxy when I make a mistake somewhere.

**Comment by landley** [comment] 2019-12-24 20:49
I used to maintain busybox, and started toybox when I left busybox? (I really should have called the project "dorodango" instead, ala http://www.dorodango.com/ , but that's hindsight for you.)

Stuff was written about it at the time, and I gave a talk about it a couple months back. Possibly I should add these links to https://landley.net/toybox/about.html ?

https://lwn.net/Articles/202106/
https://lwn.net/Articles/478308/
https://www.youtube.com/watch?v=MkJkyMuBm3g

I merged the basic mkroot plumbing into toybox (as "make root") a while back, but in order for it to "boot to shell prompt with working net" I need a reasonably complete toysh (that's what I'm poking at now) and to promote route.c out of pending (it needs a complete rewrite to use the netlink api instead, see https://android.googlesource.com/platform/external/toybox/+/48e1f81151f6 ). The external mkroot was using busybox for those, the one in toybox just uses toybox and the linux kernel source you point it at with LINUX=/path/to/source , but that means I've got 2 missing dependencies before I can even _start_ on the native build environment.

I've also been regression testing toybox in my old aboriginal linux project (https://landley.net/notes-2019.html#19-11-2019), and maybe I should push a branch of that to github and mention it on https://landley.net/aboriginal but I really don't want to put too much effort into that when mkroot is replacing it. https://bkhome.org/news/201803/aboriginal-linux-120x-resuscitated.html did a fork last year if you're interested, or maybe https://blogs.gnome.org/tvb/2016/03/23/aboriginal-ybd-an-exploration-in-cross-building/ would still be interested? I was just going "can I jump straight into the old https://github.com/landley/control-images Linux From Scratch build using new toybox" and the answer was "no, because uClibc->musl version skew breaks the old LFS build and getting current toybox to build under a 10 year old version of uClibc isn't worth it".)

**Comment by firasuke** [comment] 2019-12-24 21:50
@landley, I'd like to thank you for your awesome work on toybox.

I'd also like to report that I was able to build an extremely modified version of the latest LFS that uses musl, s6 and many other lighter components such as zlib-ng, libedit, POSIX bc, slibtool, lbzip2, netbsd-curses, pkgconf, libcap-ng, dash, gettext-tiny, libressl, samurai, pigz, smdev... and many more, using toybox.

The project is called [glaucus](https://github.com/glaucuslinux/glaucus), and it previously used a mix of sbase, ubase and lobase (OpenBSD base port to Linux) to provide a basic userland  (in fact you can fire up QEMU and test one of the older versions located in the [Releases](https://github.com/glaucuslinux/glaucus/releases) section).

The previous userland lacked a lot in functionality as I wasn't able to bootstrap the system at all after performing a chroot. But when I switched to toybox, I was able to bootstrap the entire system!

Furthermore, toybox used around 200 KB less storage than my previous userland (which was around 500 - 600 KB, so that's at least a 30 % reduction in size based on my toybox configuration).

The only tool from toybox that didn't work as I expected is the `install` command. I found it not accepting the `-t` flag and performing stripping on files regardless if they're executables or just regular text files or scripts.

Other than that, everything worked as expected (I only had to modify the format in which ls prints time to please several configure scripts, but that's it)!

Keep up the great work!

**Comment by landley** [comment] 2019-12-24 22:36
Cool! (Samurai... ah, probably https://github.com/SamuraiWTF/samuraiwtf .) Your project's website does not appear to be up yet...

Heh, install doesn't get quite as much testing as it should because "make test_install" would call "make install" which... has another meaning. :)

Ok, you need install -t added, and there's a bug with unnecessary stripping, which... I don't understand? (Can I get a test case?) When you say -s, install calls strip (the external one, generally from binutils), do you only want -s to only call strip for certain file types? Because the debian one isn't _not_ stripping text files:

  $ echo hello > blah
  $ install -s blah blah2
  strip:blah2: File format not recognized
  install: strip process terminated abnormally
  $ install blah blah3
  $ 

Rob

**Comment by firasuke** [comment] 2019-12-24 23:10
@landley, Thanks!

[Samurai](https://github.com/michaelforney/samurai) as in a lightweight drop-in ninja replacement, and yes the website isn't up yet and the wiki is old so I apologize for that. I've just been really busy trying to get everything working perfectly before releasing a new version of glaucus and updating the wiki accordingly (then maybe creating a simple static website for the project).

I'm actually encountering the error when using the `-D` and `-v` flags:

**Comment by enh-google** [comment] 2020-08-11 15:43
i'm assuming http://landley.net/toybox/faq.html#why_toybox covers the initial question, and #161 is the separate bug for the install strip issue that came up later on this thread, so nothing left to do here.

**Closed by enh-google** 2020-08-11 15:43 UTC
