### ISSUE TITLE
Broken netcat on Darwin since recent changes

### ISSUE THREAD

**Issue by geoff-nixon** [landley/toybox#132] opened 2019-07-20 08:16 UTC
The improvements made in a55b7d7 and a57721d1 breaks compilation of netcat.c on Darwin. No `SOCK_CLOEXEC`. Not sure if the fix in https://github.com/ArduPilot/ardupilot/issues/8592 would do the trick?

**Comment by landley** [comment] 2019-07-20 20:10
Hmmm, happy to break it up but I need a way to signal to xsocket() that it should call the fcntl.

The easy thing seems to be to #define SOCK_CLOEXEC in portability.h and then either move xsocket() to portability.c and have an apple version, or add a check if it's the new constant (something like SOCK_CLOEXEC == 0xc0000000 which sets the top _two_ bits and thus should never be used as a real value, and the test drop out as a compile time constant comparison on other platforms) and do the fcntl then.

Unfortunately either way requires #defining SOCK_CLOEXEC for the callers, and I can't look at the apple headers to see what's a safe value to define it to because proprietary, but I'm guessing they're the same as freebsd?

**Comment by geoff-codes** [comment] 2019-07-21 00:00
In this case, they're highly modified versions derived from OpenBSD.
Here's how libressl handles it:
https://github.com/libressl-portable/portable/tree/master/apps/nc/compat

**Comment by enh-google** [comment] 2019-09-01 04:32
(patch sent to list.)

**Comment by enh-google** [comment] 2019-09-05 21:09
@landley --- i can confirm this is fixed by b8be71f842333bf5ebfed6ee70626b1870d2a7d0.

**Comment by landley** [comment] 2019-09-05 23:29
Yay.

**Closed by landley** 2019-09-05 23:29 UTC
